# Generated by Django 2.1.1 on 2020-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='date',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Aadhar_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='AADHAR'),
        ),
    ]
